version: "3"

services:
  react-app-dev:
    image: bam/react-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - "./src:/opt/app/src"
      - "/opt/app/node_modules"

  react-app-prod:
    image: bam/react-app:v1
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80